### ISSUE TITLE
Image not displayed in blog post

### ISSUE THREAD

**Issue by Squadrick** [Project-MANAS/projectmanas.in#1]
The image is not displayed properly in [this blog post](http://projectmanas.in/2019/05/28/ai-vs-hi.html). Screenshot [here](https://i.imgur.com/YeEWL74.png).

Tested on Chrome and Firefox.

**Comment by Squadrick** [comment]
cc: @Sarath18

**Comment by aneesh404** [comment]
Fixed the issue. Something caused the image to break. Compressed the image and now it's displayed.

**Comment by Squadrick** [comment]
This seems to be broken again. 

@aneesh404 could you take a look at this?

**Comment by shrijitsingh99** [comment]
Resolved e1e052f579c28069447beabd30b935281b053e94
