### ISSUE TITLE
Fix Solo description in landing page

### ISSUE THREAD

**Issue by Squadrick** [Project-MANAS/projectmanas.in#11]
We currently use a default caption: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna" on [Solo's landing page](http://projectmanas.in/solo). Replace this with something meaningful.

**Comment by shrijitsingh99** [comment]
How about this?
"Solo, it's the UGV that made the headlines at IGVC in less than twelve months after his elder brother Adam's entry. Overcoming the shortcomings faced, Solo showcases our team's technical abilities and ability to overcome any challenge."

Reference: https://starwars.fandom.com/wiki/Kessel_Run/Legends

**Comment by Squadrick** [comment]
Replace "his elder brother" with "its predecessor"

**Comment by shrijitsingh99** [comment]
What about replacing "Solo" with "You've never heard of Solo?".
Staying true to the movie

**Comment by trickarcher** [comment]
Lol. The management is going to be furious. On a serious note.can we omit the Overcoming challenges sentence. I think the success speaks for itself.
