### ISSUE TITLE
No favicon for blog posts

### ISSUE THREAD

**Issue by Squadrick** [Project-MANAS/projectmanas.in#8]
The blog posts don't display the manas logo as a favicon. It displays the default icon.

See [this](http://projectmanas.in/2019/05/28/ai-vs-hi.html) and [this](http://projectmanas.in/2019/03/14/deep-learning.html).

**Comment by trickarcher** [comment]
Fixed here. e1e052f579c28069447beabd30b935281b053e94. The issue was resolved by removing all large files from GIT LFS.
